font_family JetBrains Mono NF
font_size 11.0
modify_font cell_height 120%

bold_font auto
italic_font auto
bold_italic_font auto

cursor_shape block

remember_window_size yes


# =======================
# 	COLOR THEME
# =======================

foreground #B0B0B0
background #000000
# background #101010

selection_foregorund #B0B0B0
selection_background #272727

cursor #B0B0B0
cursor_text_color #101010

url_color #8EBEEC
active_border_color #272727
inactive_border_color #272727

