general {
    disable_loading_bar = true
    hide_cursor = false
    grace = 0
    no_fade_in = true
    no_fade_out = true
}

background {
    monitor =
    color = rgb(000000)
}

# Top bar
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
    color = rgb(ffffff)
    font_family = JetBrains Mono NF, monospace
    font_size = 13
    font_weight = 600
    position = 0, -20
    halign = center
    valign = top
}

# Center label and input
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M:%S')"
    color = rgb(ffffff)
    font_family = JetBrains Mono NF, monospace
    font_size = 46
    font_weight = 600
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(ffffff)
    font_family = JetBrains Mono NF
    font_size = 14
    font_weight = 600
    position = 0, 40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 240, 42
    outline_thickness = 1
    rounding = 0
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true

    outer_color = rgb(ffffff)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    check_color = rgb(4c7899)
    fail_color = rgb(e53935)

    font_family = JetBrains Mono NF
    placeholder_text = <span foreground="##555555">password</span>
    fade_on_empty = false

    position = 0, -60
    halign = center
    valign = center
}
