console_title_template = "{{ .Shell }} in {{ .Folder }}"
version = 3
final_space = true

[palette]
  os = "#ACB0BE"
  closer = "p:os"
  pink = "#F4B8E4"
  lavander = "#BABBF1"
  blue = "#8CAAEE"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "p:os"
    template = "{{.Icon}}"

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "p:blue"
    template = "{{ .UserName }}@{{ .HostName }}"

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:pink"
    template = "{{ .Path }}"

    [blocks.segments.properties]
      folder_icon = "..\ue5fe"
      home_icon = "~"
      style = "agnoster_short"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:lavander"
    template = "{{ .HEAD }}"

    [blocks.segments.properties]
      branch_icon = "\ue725"
      cherry_pick_icon = "\ue29b"
      commit_icon = "\uf417"
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = "\ue727"
      no_commits_icon = "\uf0c3"
      rebase_icon = "\ue728"
      revert_icon = "\uf0e2"
      tag_icon = "\uf412"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:closer"
    template = "\uf105"
