[env]
TERM = "xterm-256color"

[window]
opacity = 0.65
decorations = "full"
dynamic_padding = true
padding = { x = 10, y = 8 }

[font]
size = 12.0
normal = { family = "Cascadia Mono NF", style = "Regular" }
bold = { family = "Cascadia Mono NF", style = "Bold" }
italic = { family = "Cascadia Mono NF", style = "Italic" }
bold_italic = { family = "Cascadia Mono NF", style = "Bold Italic" }

builtin_box_drawing = true

[colors.primary]
background = "#000000"

[mouse]
hide_when_typing = true
