require("core.options")
require("core.keymaps")
require("core.color-themes")

require("plugins.lsp.lspconfig")
require("plugins.lsp.mason")

require("plugins.autopairs")
require("plugins.blink")
require("plugins.bufferline")
require("plugins.dap")
require("plugins.explorer")
require("plugins.nvim-colorizer")
require("plugins.nvim-surround")
require("plugins.smear-cursor")
require("plugins.status-line")
require("plugins.telescope")
require("plugins.treesitter")

vim.cmd(":colorscheme koda")
